GET https://apim-johwer.azure-api.net/ch2/sessions
Ocp-Apim-Subscription-Key: 6731b815b19a4db884500292691042e8

###

https://ca-customerapi.greensmoke-b90f0886.eastus2.azurecontainerapps.io/api/customers